// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"context"
	"mockserver/internal/logging"
	"mockserver/internal/tracking"
	"net/http"
)

// GeneratedHandlers returns all generated handlers.
func GeneratedHandlers(ctx context.Context, dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) []*GeneratedHandler {
	return []*GeneratedHandler{
		NewGeneratedHandler(ctx, http.MethodGet, "/pets", pathGetPets(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodGet, "/pets/{petId}", pathGetPetsPetID(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodPost, "/pets", pathPostPets(dir, rt)),
	}
}
