// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type User struct {
	ID        *int64  `json:"id,omitempty"`
	Username  *string `json:"username,omitempty"`
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Email     *string `json:"email,omitempty"`
	Password  *string `json:"password,omitempty"`
	Phone     *string `json:"phone,omitempty"`
	// User Status
	UserStatus *int `json:"userStatus,omitempty"`
}

func (o *User) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *User) GetUsername() *string {
	if o == nil {
		return nil
	}
	return o.Username
}

func (o *User) GetFirstName() *string {
	if o == nil {
		return nil
	}
	return o.FirstName
}

func (o *User) GetLastName() *string {
	if o == nil {
		return nil
	}
	return o.LastName
}

func (o *User) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *User) GetPassword() *string {
	if o == nil {
		return nil
	}
	return o.Password
}

func (o *User) GetPhone() *string {
	if o == nil {
		return nil
	}
	return o.Phone
}

func (o *User) GetUserStatus() *int {
	if o == nil {
		return nil
	}
	return o.UserStatus
}
