// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

// Status values that need to be considered for filter
type Status string

const (
	StatusAvailable Status = "available"
	StatusPending   Status = "pending"
	StatusSold      Status = "sold"
)

func (e Status) ToPointer() *Status {
	return &e
}
func (e *Status) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "available":
		fallthrough
	case "pending":
		fallthrough
	case "sold":
		*e = Status(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Status: %v", v)
	}
}

type FindPetsByStatusTypesRequest struct {
	// Status values that need to be considered for filter
	Status *Status `default:"available" queryParam:"style=form,explode=true,name=status"`
}

func (f FindPetsByStatusTypesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FindPetsByStatusTypesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *FindPetsByStatusTypesRequest) GetStatus() *Status {
	if o == nil {
		return nil
	}
	return o.Status
}

type FindPetsByStatusTypesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	Pets []components.Pet
}

func (o *FindPetsByStatusTypesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *FindPetsByStatusTypesResponse) GetPets() []components.Pet {
	if o == nil {
		return nil
	}
	return o.Pets
}
