// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type LoginUserRequest struct {
	// The user name for login
	Username *string `queryParam:"style=form,explode=true,name=username"`
	// The password for login in clear text
	Password *string `queryParam:"style=form,explode=true,name=password"`
}

func (o *LoginUserRequest) GetUsername() *string {
	if o == nil {
		return nil
	}
	return o.Username
}

func (o *LoginUserRequest) GetPassword() *string {
	if o == nil {
		return nil
	}
	return o.Password
}

type LoginUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// successful operation
	String  *string
	Headers map[string][]string
}

func (o *LoginUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *LoginUserResponse) GetString() *string {
	if o == nil {
		return nil
	}
	return o.String
}

func (o *LoginUserResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
