// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type PetTest90324ewrewrewResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// unexpected error
	Error *components.Error
}

func (o *PetTest90324ewrewrewResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PetTest90324ewrewrewResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
