// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type ShowRequest struct {
	// The id of the pet to retrieve
	PetID string `pathParam:"style=simple,explode=false,name=petId"`
}

func (o *ShowRequest) GetPetID() string {
	if o == nil {
		return ""
	}
	return o.PetID
}

type ShowResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Expected response to a valid request
	Pet *components.Pet
	// unexpected error
	Error *components.Error
}

func (o *ShowResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ShowResponse) GetPet() *components.Pet {
	if o == nil {
		return nil
	}
	return o.Pet
}

func (o *ShowResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
