// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UpdateUserRequest struct {
	// name that needs to be updated
	Username string `pathParam:"style=simple,explode=false,name=username"`
	// Update an existent user in the store
	User *components.User `request:"mediaType=application/json"`
}

func (o *UpdateUserRequest) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}

func (o *UpdateUserRequest) GetUser() *components.User {
	if o == nil {
		return nil
	}
	return o.User
}

type UpdateUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *UpdateUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
