/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assert, it } from "vitest";

it.skip("Pets Sdk List Pets", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step listPets.test referencing operation listPets not found in document`]",
  );
});

it.skip("Pets Sdk Pet Test90324ewrewrew", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step PetTest90324ewrewrew.test referencing operation PetTest90324ewrewrew not found in document`]",
  );
});

it.skip("Pets Sdk Show", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step show.test referencing operation show not found in document`]",
  );
});
