/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { Pets } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Pets Sdk List Pets", async () => {
  const pets = new Pets({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: createTestHTTPClient("listPets"),
  });

  const result = await pets.pets.listPets({});
  expect(result).toBeDefined();
  expect(result.result).toBeDefined();
  expect(result.result).toEqual([
    {
      id: 767425,
      name: "<value>",
    },
  ]);
});

test("Pets Sdk Pet Test90324ewrewrew", async () => {
  const pets = new Pets({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: createTestHTTPClient("PetTest90324ewrewrew"),
  });

  const result = await pets.pets.petTest90324ewrewrew({
    id: 841329,
    name: "<value>",
  });
});

test("Pets Sdk Show", async () => {
  const pets = new Pets({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: createTestHTTPClient("show"),
  });

  const result = await pets.pets.show({
    petId: "<id>",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    id: 52777,
    name: "<value>",
  });
});
