workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    petstore-oas:
        inputs:
            - location: before-overlay-swagger.json
        overlays:
            - location: overlay.yml
        output: test.json
        registry:
            location: registry.speakeasyapi.dev/ryan-local/ryan-telemetry/petstore-oas
targets: {}
