workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    petstore-oas:
        inputs:
            - location: ../openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/ryan-local/ryan-telemetry/petstore-oas
targets:
    petstore:
        target: typescript
        source: petstore-oas
        output: sdk
        publish:
            npm:
                token: $npm_token
