/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Status values that need to be considered for filter
 */
export const Status = {
  Available: "available",
  Pending: "pending",
  Sold: "sold",
} as const;
/**
 * Status values that need to be considered for filter
 */
export type Status = ClosedEnum<typeof Status>;

export type FindPetsByStatusTypesRequest = {
  /**
   * Status values that need to be considered for filter
   */
  status?: Status | undefined;
};

/** @internal */
export const Status$inboundSchema: z.ZodNativeEnum<typeof Status> = z
  .nativeEnum(Status);

/** @internal */
export const Status$outboundSchema: z.ZodNativeEnum<typeof Status> =
  Status$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Status$ {
  /** @deprecated use `Status$inboundSchema` instead. */
  export const inboundSchema = Status$inboundSchema;
  /** @deprecated use `Status$outboundSchema` instead. */
  export const outboundSchema = Status$outboundSchema;
}

/** @internal */
export const FindPetsByStatusTypesRequest$inboundSchema: z.ZodType<
  FindPetsByStatusTypesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: Status$inboundSchema.default("available"),
});

/** @internal */
export type FindPetsByStatusTypesRequest$Outbound = {
  status: string;
};

/** @internal */
export const FindPetsByStatusTypesRequest$outboundSchema: z.ZodType<
  FindPetsByStatusTypesRequest$Outbound,
  z.ZodTypeDef,
  FindPetsByStatusTypesRequest
> = z.object({
  status: Status$outboundSchema.default("available"),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FindPetsByStatusTypesRequest$ {
  /** @deprecated use `FindPetsByStatusTypesRequest$inboundSchema` instead. */
  export const inboundSchema = FindPetsByStatusTypesRequest$inboundSchema;
  /** @deprecated use `FindPetsByStatusTypesRequest$outboundSchema` instead. */
  export const outboundSchema = FindPetsByStatusTypesRequest$outboundSchema;
  /** @deprecated use `FindPetsByStatusTypesRequest$Outbound` instead. */
  export type Outbound = FindPetsByStatusTypesRequest$Outbound;
}

export function findPetsByStatusTypesRequestToJSON(
  findPetsByStatusTypesRequest: FindPetsByStatusTypesRequest,
): string {
  return JSON.stringify(
    FindPetsByStatusTypesRequest$outboundSchema.parse(
      findPetsByStatusTypesRequest,
    ),
  );
}

export function findPetsByStatusTypesRequestFromJSON(
  jsonString: string,
): SafeParseResult<FindPetsByStatusTypesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FindPetsByStatusTypesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FindPetsByStatusTypesRequest' from JSON`,
  );
}
