/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as components from "../components/index.js";

export type ShowRequest = {
  /**
   * The id of the pet to retrieve
   */
  petId: string;
};

export type ShowResponse = components.ErrorT | components.Pet;

/** @internal */
export const ShowRequest$inboundSchema: z.ZodType<
  ShowRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  petId: z.string(),
});

/** @internal */
export type ShowRequest$Outbound = {
  petId: string;
};

/** @internal */
export const ShowRequest$outboundSchema: z.ZodType<
  ShowRequest$Outbound,
  z.ZodTypeDef,
  ShowRequest
> = z.object({
  petId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ShowRequest$ {
  /** @deprecated use `ShowRequest$inboundSchema` instead. */
  export const inboundSchema = ShowRequest$inboundSchema;
  /** @deprecated use `ShowRequest$outboundSchema` instead. */
  export const outboundSchema = ShowRequest$outboundSchema;
  /** @deprecated use `ShowRequest$Outbound` instead. */
  export type Outbound = ShowRequest$Outbound;
}

/** @internal */
export const ShowResponse$inboundSchema: z.ZodType<
  ShowResponse,
  z.ZodTypeDef,
  unknown
> = z.union([components.ErrorT$inboundSchema, components.Pet$inboundSchema]);

/** @internal */
export type ShowResponse$Outbound =
  | components.ErrorT$Outbound
  | components.Pet$Outbound;

/** @internal */
export const ShowResponse$outboundSchema: z.ZodType<
  ShowResponse$Outbound,
  z.ZodTypeDef,
  ShowResponse
> = z.union([components.ErrorT$outboundSchema, components.Pet$outboundSchema]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ShowResponse$ {
  /** @deprecated use `ShowResponse$inboundSchema` instead. */
  export const inboundSchema = ShowResponse$inboundSchema;
  /** @deprecated use `ShowResponse$outboundSchema` instead. */
  export const outboundSchema = ShowResponse$outboundSchema;
  /** @deprecated use `ShowResponse$Outbound` instead. */
  export type Outbound = ShowResponse$Outbound;
}
