/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { petsListPets } from "../funcs/petsListPets.js";
import { petsShowPetById } from "../funcs/petsShowPetById.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Pets extends ClientSDK {
  /**
   * List all pets
   */
  async listPets(
    request: operations.ListPetsRequest,
    options?: RequestOptions,
  ): Promise<operations.ListPetsResponse> {
    return unwrapAsync(petsListPets(
      this,
      request,
      options,
    ));
  }

  /**
   * Info for a specific pet
   */
  async showPetById(
    request: operations.ShowPetByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.ShowPetByIdResponse> {
    return unwrapAsync(petsShowPetById(
      this,
      request,
      options,
    ));
  }
}
