/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { PetsSDK } from "./petssdk.js";

export class Pets extends ClientSDK {
  private _petsSDK?: PetsSDK;
  get petsSDK(): PetsSDK {
    return (this._petsSDK ??= new PetsSDK(this._options));
  }
}
